characters:
- id: monika
  name: Monika
  path: characters/monika/character.json
- id: alice
  name: Alice
  path: characters/alice/character.json
- id: jingyu
  name: 鲸鱼娘
  path: characters/jingyu/character.json
default: jingyu
